language: php
php:
  - 5.5
  - 5.4
  - 5.6
  - 7.0
  - hhvm
services:
  - mysql
env:
  - DB=mysql
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS crudnative;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_$DB.xml --coverage-text
